### ISSUE TITLE
Many players experiencing softlocks on 1.9 

### ISSUE THREAD

**Issue by StaneDaynus** [Kylemc1413/MappingExtensions#9]
I just wanted to bring it to the attention of the people who actually know how to deal with this, upon entering maps that utilize the mod you are greeted with a soft lock\black screen.
Rift S\Steam version is all I can confirm. Thanks.

**Comment by Kylemc1413** [comment]
This is a compatibility issue with CustomJSONData and Left Handed Mode/No Obstacles/No Bombs that is fixed in 1.4.1 which was approved on beatmods as of this morning

**Comment by StaneDaynus** [comment]
Unfortunately me and others are still unable to play songs such as The wall, speed me up, unholy crusade ect on 1.9 (all maps that utilize extensions) The soft lock persists, any recommendations?

**Comment by Kylemc1413** [comment]
That's likely an issue with Chroma/Noodle Extensions, as Unholy Crusade does not use mapping extensions

**Comment by StaneDaynus** [comment]
That’s strange. It says mods required are chroma and mapping extension. Chroma is functional in other maps. Thanks for the prompt reply. I’ll probably just instruct others seeking answers to roll back to 1.8.

**Comment by Kylemc1413** [comment]
Going to 1.8 wouldn't fix the issue considering it's most certainly a mod issue and 1.8 and 1.9 have the same mods overall

**Comment by Kylemc1413** [comment]
And as for Unholy Crusade, note
![image](https://user-images.githubusercontent.com/21244037/79052930-c0d4ac80-7c07-11ea-8d23-35c083c32835.png) how it uses **Noodle** Extensions rather than mapping extensions

**Comment by StaneDaynus** [comment]
Yeah I was incorrect about unholy crusade. I can now confirm that Speed me up as well as the wall works on 1.8 and not on 1.9 as an example. Mods required: map extensions. I have confirmed with 4 other people that map extensions are not functional still on 1.9 on reddit. I’m not trying to be rude or anything. Just informing.

**Comment by StaneDaynus** [comment]
Nevermind. You’re correct. Chroma / just rainbow lights are now the ones having issues on 1.9 and not 1.8. Carry on lmao
